import re

from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.audit import AuditLog
from app.models.document import Document, DocumentStatus
from app.models.pdf_export import PdfExport, PdfExportStatus
from app.models.user import User
from app.services.simple_pdf import render_study_document_pdf
from app.services.template_ids import is_blue_certification_template, is_main_template


def _pdf_filename(document: Document) -> str:
    words = re.findall(r"[A-Za-z0-9]+", str(document.title or ""))
    stem = "-".join(word.lower() for word in words[:4]) or "study-document"
    return f"{stem}-{str(document.id)[:8]}.pdf"


def render_pdf_export(db: Session, document: Document, user: User) -> PdfExport:
    latest_version = sorted(document.versions, key=lambda version: version.version_number)[-1] if document.versions else None
    content = latest_version.content if latest_version else {
        "title_page": document.title,
        "introduction": "This PDF export was generated by StudyMint AI.",
        "sections": [],
        "key_points": [],
        "examples": [],
        "study_questions": [],
        "conclusion": "",
        "metadata": {},
        "question_bank": [],
    }
    filename = _pdf_filename(document)
    output_path = settings.export_dir_path / filename
    render_study_document_pdf(content, document.template_id, output_path)

    if is_blue_certification_template(document.template_id):
        renderer = "simple_pdf_blue_certification_test_bank"
    elif is_main_template(document.template_id):
        renderer = "simple_pdf_exam_bundle"
    else:
        renderer = "simple_pdf"

    export = PdfExport(
        tenant_id=document.tenant_id,
        document_id=document.id,
        status=PdfExportStatus.COMPLETED.value,
        pdf_url=f"{settings.PDF_EXPORT_BASE_URL}/{filename}",
        renderer=renderer,
    )
    document.status = DocumentStatus.PDF_READY.value
    db.add(export)
    db.add(
        AuditLog(
            tenant_id=document.tenant_id,
            user_id=user.id,
            action="pdf_export.created",
            resource_type="document",
            resource_id=document.id,
            event_metadata={"renderer": renderer},
        )
    )
    db.commit()
    db.refresh(export)
    return export
